// mockData.js
export const mockSongs = [
  { id: 1, title: 'Song 1', coverImage: '/Assets/Album.jpg' },
  { id: 2, title: 'Song 2', coverImage: '/Assets/Album1.jpg' },
  { id: 3, title: 'Song 3', coverImage: '/Assets/Album2.jpg' },
  { id: 4, title: 'Song 4', coverImage: '/Assets/Album3.jpg' },
  { id: 5, title: 'Song 5', coverImage: '/Assets/Album4.jpg' },
  { id: 6, title: 'Song 6', coverImage: '/Assets/Album5.jpg' },
  { id: 7, title: 'Song 7', coverImage: '/Assets/Album6.jpg' },
  { id: 8, title: 'Song 8', coverImage: '/Assets/Album7.jpg' },
  { id: 9, title: 'Song 9', coverImage: '/Assets/Album8.jpg' },
  { id: 10, title: 'Song 10', coverImage: '/Assets/Album9.jpg' },
];

export const mockAlbums = [
  {
    id: 1,
    title: 'Album 1',
    description: 'a bit of a description about this album',
    coverImage: '/Assets//Album10.jpg',
    songs: [
      { id: 1, title: 'Song 1' },
      { id: 2, title: 'Song 2' },
      { id: 3, title: 'Song 3' },
      { id: 4, title: 'Song 4' },
      { id: 5, title: 'Song 5' },
      { id: 6, title: 'Song 6' },
      { id: 7, title: 'Song 7' },
      { id: 8, title: 'Song 8' },
    ],
  },
  {
    id: 2,
    title: 'Album 2',
    description: 'a bit of a description about this album',
    coverImage: '/Assets//Album11.jpg',
    songs: [
      { id: 9, title: 'Song 9' },
      { id: 10, title: 'Song 10' },
      { id: 11, title: 'Song 11' },
      { id: 12, title: 'Song 12' },
      { id: 13, title: 'Song 13' },
      { id: 14, title: 'Song 14' },
      { id: 15, title: 'Song 15' },
      { id: 16, title: 'Song 16' },
    ],
  },
  {
    id: 3,
    title: 'Album 3',
    description: 'a bit of a description about this album',
    coverImage: '/Assets//Album12.jpg',
    songs: [
      { id: 17, title: 'Song 17' },
      { id: 18, title: 'Song 18' },
      { id: 19, title: 'Song 19' },
      { id: 20, title: 'Song 20' },
      { id: 21, title: 'Song 21' },
      { id: 22, title: 'Song 22' },
      { id: 23, title: 'Song 23' },
      { id: 24, title: 'Song 24' },
    ],
  },
  {
    id: 4,
    title: 'Album 4',
    description: 'a bit of a description about this album',
    coverImage: '/Assets//Album13.jpg',
    songs: [
      { id: 25, title: 'Song 17' },
      { id: 26, title: 'Song 18' },
      { id: 27, title: 'Song 19' },
      { id: 28, title: 'Song 20' },
      { id: 29, title: 'Song 21' },
      { id: 30, title: 'Song 22' },
      { id: 31, title: 'Song 23' },
      { id: 32, title: 'Song 24' },
    ],
  },
  {
    id: 4,
    title: 'Album 4',
    description: 'a bit of a description about this album',
    coverImage: '/Assets/Album14.jpg',
    songs: [
      { id: 33, title: 'Song 17' },
      { id: 34, title: 'Song 18' },
      { id: 35, title: 'Song 19' },
      { id: 36, title: 'Song 20' },
      { id: 37, title: 'Song 21' },
      { id: 38, title: 'Song 22' },
      { id: 39, title: 'Song 23' },
      { id: 40, title: 'Song 24' },
    ],
  },
  {
    id: 5,
    title: 'Album 5',
    description: 'a bit of a description about this album',
    coverImage: '/Assets/Album15.jpg',
    songs: [
      { id: 41, title: 'Song 17' },
      { id: 42, title: 'Song 18' },
      { id: 43, title: 'Song 19' },
      { id: 44, title: 'Song 20' },
      { id: 45, title: 'Song 21' },
      { id: 46, title: 'Song 22' },
      { id: 47, title: 'Song 23' },
      { id: 48, title: 'Song 24' },
    ],
  },
];


export const mockPodcasts = [
  { id: 1, title: 'Podcast 1', coverImage: '/Assets/Album16.jpg', description: 'a bit of a description about this album' },
  { id: 2, title: 'Podcast 2', coverImage: '/Assets/Album17.jpg', description: 'a bit of a description about this album' },
  { id: 3, title: 'Podcast 3', coverImage: '/Assets/Album.jpg', description: 'a bit of a description about this album' },
  { id: 4, title: 'Podcast 4', coverImage: '/Assets/Album1.jpg', description: 'a bit of a description about this album' },
  { id: 5, title: 'Podcast 5', coverImage: '/Assets/Album2.jpg', description: 'a bit of a description about this album' },
  { id: 6, title: 'Podcast 6', coverImage: '/Assets/Album16.jpg', description: 'a bit of a description about this album' },
];

export const mockArtists = [
  { id: 1, title: 'Artist 1', coverImage: '/Assets/Album3.jpg' },
  { id: 2, title: 'Artist 2', coverImage: '/Assets/Album4.jpg' },
  { id: 3, title: 'Artist 3', coverImage: '/Assets/Album5.jpg' },
  { id: 4, title: 'Artist 4', coverImage: '/Assets/Album6.jpg' },
  { id: 5, title: 'Artist 5', coverImage: '/Assets/Album7.jpg' },
  { id: 6, title: 'Artist 6', coverImage: '/Assets/Album8.jpg' },
];
